# Generated by Django 3.2.6 on 2021-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptname', models.CharField(blank=True, max_length=50, null=True)),
                ('kananame', models.CharField(blank=True, max_length=50, null=True)),
                ('patientid', models.CharField(blank=True, max_length=20, null=True)),
                ('felicaid', models.CharField(blank=True, max_length=30, null=True)),
                ('ordername', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('rp', 'rp'), ('iv', 'iv'), ('doc', 'doc'), ('jihi_other', 'jihi_other'), ('txt', 'txt')], default='', max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_kana', models.CharField(max_length=50)),
                ('fullname_kanji', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('patientid', models.IntegerField(blank=True, null=True)),
                ('tel_number', models.CharField(max_length=13)),
                ('postal_code', models.CharField(max_length=8)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('insurer_id', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
