# Generated by Django 3.2.6 on 2021-08-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermenu',
            name='patient',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(),
        ),
    ]
