# Generated by Django 3.2.6 on 2021-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='category',
            field=models.CharField(blank=True, choices=[('渡航ワクチン', '渡航ワクチン'), ('美容健康注射', '美容健康注射'), ('ビタミン剤', 'ビタミン剤'), ('一般ワクチン', '一般ワクチン'), ('アフターピル・低用量ピル', 'アフターピル・低用量ピル'), ('美容薬品', '美容薬品'), ('トラベル予防薬', 'トラベル予防薬'), ('ED治療薬', 'ED治療薬'), ('ヘルスチェック・健康診断', 'ヘルスチェック・健康診断'), ('疲労回復注射', '疲労回復注射'), ('AGA治療薬', 'AGA治療薬'), ('その他・ご相談', 'その他・ご相談')], default='', max_length=50, null=True, unique=True),
        ),
    ]
