# Generated by Django 3.2.6 on 2021-09-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210819_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientno', models.IntegerField()),
                ('ordername', models.CharField(max_length=100)),
            ],
        ),
    ]
