# Generated by Django 3.2.6 on 2021-09-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210912_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address1',
            new_name='address',
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='ivtype',
            field=models.CharField(blank=True, choices=[('静脈注射', '静脈注射'), ('筋肉注射', '筋肉注射'), ('皮下注射', '皮下注射'), ('点滴注射', '点滴注射'), ('皮内注射', '皮内注射'), ('その他注射', 'その他注射')], default='', max_length=10, null=True),
        ),
    ]
