# Generated by Django 3.2.6 on 2021-09-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_postdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDetail',
        ),
    ]
