# Generated by Django 3.2.6 on 2021-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delete_postdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptname', models.CharField(max_length=50)),
                ('patientid', models.IntegerField()),
                ('felicaid', models.CharField(max_length=30)),
                ('ordername', models.CharField(max_length=200)),
            ],
        ),
    ]
