# Generated by Django 3.2.6 on 2021-09-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
