# Generated by Django 3.2.6 on 2021-09-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_ordermenu_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='patientid',
            field=models.CharField(max_length=20),
        ),
    ]
