# Generated by Django 3.2.6 on 2021-09-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderdetail_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='type',
            field=models.CharField(blank=True, choices=[('rp', 'rp'), ('iv', 'iv'), ('doc', 'doc'), ('jihi_other', 'jihi_other'), ('txt', 'txt')], default='', max_length=10, null=True, unique=True),
        ),
    ]
